In [32]:
import pandas as pd
from geopy.geocoders import Nominatim

In [33]:
data = pd.read_csv('prueba_fetchdata_metrobus.csv')

In [34]:
columns = list(data.columns)

In [35]:
columns

['id',
 'date_updated',
 'vehicle_id',
 'vehicle_label',
 'vehicle_current_status',
 'position_latitude',
 'position_longitude',
 'geographic_point',
 'position_speed',
 'position_odometer',
 'trip_schedule_relationship',
 'trip_id',
 'trip_start_date',
 'trip_route_id']

In [36]:
list_aux = list(data['geographic_point'])

In [48]:
#from geopy.geocoders import Nominatim
def geolocaliza(coordenadas):
    geolocator = Nominatim(user_agent="prueba")
    location = geolocator.reverse(coordenadas)
    #print(location[0])
    try:
        ubica = location[0]
    except:
        ubica = 'N/A'
    return ubica

In [49]:
ubicacion = [geolocaliza(i) for i in list_aux]

In [50]:
#def square(x): return lambda : x*x
alcaldia = []
for location in ubicacion:
    try:
        alcaldia.append(location.split(',')[-4])
    except:
        alcaldia.append('N/A')
        pass
    #print(alcaldia)

In [53]:
ubicacion

['Universidad Nacional Autónoma de México, Circuito Exterior, Ciudad Universitaria, Coyoacán, Ciudad de México, 04360, México',
 'Ayuntamiento, Avenida Insurgentes Sur, Tlalpan Centro I, Tlalpan, Ciudad de México, 14000, México',
 'Avenida Ingeniero Eduardo Molina, 2o. tramo 20 de Noviembre, Venustiano Carranza, Ciudad de México, 15300, México',
 'Metrobús Linea 2, Unidad Habitacional Ejército Constitucionalista, Iztapalapa, Ciudad de México, 09220, México',
 'Avenida Canal de Tezontle, Leyes de Reforma 3a. Sección, Iztapalapa, Ciudad de México, 09310, México',
 'Avenida Constitución de Apatzingán, Reforma Educativa, Iztapalapa, Ciudad de México, 09219, México',
 'Metrobus, Avenida de la Independencia, Jardines de Guadalupe, Nezahualcóyotl, Estado de México, 07500, México',
 'Metrobús Linea 2, Escandón, Miguel Hidalgo, Ciudad de México, 11800, México',
 'Nuevo León 2, Metrobús Linea 2, Hipódromo, Cuauhtémoc, Ciudad de México, 06100, México',
 'Balderas, Avenida Balderas, Tabacalera, Cuauhtémoc, Ciudad de México, 06030, México',
 'Calzada Vallejo, Nueva Industrial Vallejo, Gustavo A. Madero, Ciudad de México, 07700, México',
 'Avenida Cuauhtémoc, Doctores, Cuauhtémoc, Ciudad de México, 06720, México',
 'Etiopía / Plaza de la transparencia, Cuauhtémoc, Narvarte Poniente, Benito Juárez, Ciudad de México, 03020, México',
 'Chevrolet Delta, Avenida Cuauhtémoc, Centro Urbano Benito Juárez, Cuauhtémoc, Ciudad de México, 06740, México',
 'Calzada Vallejo, Ampliación Progreso Nacional, Gustavo A. Madero, Ciudad de México, 07650, México',
 'Calle Vallejo, Gustavo A. Madero, Tlalnepantla, Tlalnepantla de Baz, Estado de México, 07650, México',
 'Calzada Vallejo, Tlalnepantla, Tlalnepantla de Baz, Estado de México, 54170, México',
 'Farmacias de Descuento, Avenida Hidalgo, Tabacalera, Cuauhtémoc, Ciudad de México, 06030, México',
 'Calzada Vallejo, Gustavo A. Madero, Ciudad de México, 07640, México',
 'Guerrero, Buenavista, Cuauhtémoc, Ciudad de México, 06350, México',
 'Calzada Vallejo, Nueva Vallejo, Gustavo A. Madero, Ciudad de México, 07750, México',
 'Hidalgo, Avenida Hidalgo, Cuauhtémoc, Ciudad de México, 06050, México',
 'Ferrocarril de Cintura, Calle Héroe de Nacozari, Penitenciaría, Venustiano Carranza, Ciudad de México, 15280, México',
 'Callejón del Conde, Centro Urbano, Cuauhtémoc, Ciudad de México, 06010, México',
 'Calle Héroe de Nacozari, Penitenciaría, Venustiano Carranza, Ciudad de México, 15280, México',
 'Metrobús Linea 4, Avenida Jesús García, Buenavista, Cuauhtémoc, Ciudad de México, 06350, México',
 'Museo de la Revolucion Mexicana, Plaza de la República, Tabacalera, Cuauhtémoc, Ciudad de México, 06030, México',
 'Calle Héroes Ferrocarrileros, Buenavista, Cuauhtémoc, Ciudad de México, 06350, México',
 'San Lázaro Buena Vista ruta Sur, Avenida Ingeniero Eduardo Molina, 10 de Mayo, Venustiano Carranza, Ciudad de México, 15290, México',
 'Calzada General Ignacio Zaragoza, 7 de Julio, Venustiano Carranza, Ciudad de México, 15390, México',
 '5 de Mayo, Avenida Ingeniero Eduardo Molina, Del Obrero, Gustavo A. Madero, Ciudad de México, 07430, México',
 'Avenida Ingeniero Eduardo Molina, Escuela de tiro, Venustiano Carranza, Ciudad de México, 15380, México',
 'Poniente 140, San Andrés de Las Salinas, Azcapotzalco, Ciudad de México, 02320, México',
 'Puerto de Cozumel, Calzada San Juan de Aragón, FOVISSSTE Río de Guadalupe, Gustavo A. Madero, Ciudad de México, 07950, México',
 'Instituto Politécnico Nacional, Avenida Montevideo, Lindavista, Gustavo A. Madero, Ciudad de México, 07300, México',
 'Avenida 499, La Pradera, Gustavo A. Madero, Ciudad de México, 07500, México',
 'Delegación Gustavo A. Madero, Metrobús Línea 7, Aragón, Gustavo A. Madero, Ciudad de México, 07000, México',
 '43, Calle Hidalgo, Triunfo de la República, Gustavo A. Madero, Ciudad de México, 07069, México',
 'Calzada de los Misterios, Maza, Cuauhtémoc, Ciudad de México, 06270, México',
 'Metro Auditorio, Metrobús Línea 7, Polanco Chapultepec, Miguel Hidalgo, Ciudad de México, 11560, México',
 'Peralvillo, Calzada de los Misterios, Maza, Cuauhtémoc, Ciudad de México, 06270, México',
 'Calzada de los Misterios, Maza, Cuauhtémoc, Ciudad de México, 06270, México',
 'Avenida Paseo de la Reforma, Polanco Chapultepec, Miguel Hidalgo, Ciudad de México, 11560, México',
 'Metrobús Línea 7, Tabacalera, Cuauhtémoc, Ciudad de México, 06030, México',
 'Hospital Infantil La Villa, Metrobús Línea 7, Triunfo de la República, Gustavo A. Madero, Ciudad de México, 07069, México',
 'Garibaldi, Metrobús Línea 7, Tabacalera, Cuauhtémoc, Ciudad de México, 06030, México',
 'Xola, Narvarte Oriente, Benito Juárez, Ciudad de México, 03023, México',
 'El Caminero, Metrobús Linea 1, Barrio El Truenito, Tlalpan, Ciudad de México, 14430, México',
 'Cumbé Coffee Roasters, Avenida Insurgentes Sur, Roma Norte, Cuauhtémoc, Ciudad de México, 06700, México',
 'Metrobús Linea 1, Santa Isabel Tola, Gustavo A. Madero, Ciudad de México, 07010, México',
 'Durango, Metrobús Línea 1, Roma Norte, Cuauhtémoc, Ciudad de México, 06700, México',
 'La Piedad, Metrobús Linea 1, Del Valle, Benito Juárez, Ciudad de México, 03103, México',
 'CONABIO, Avenida Insurgentes Sur, Peña Pobre, Tlalpan, Ciudad de México, 14060, México',
 'Oxxo, Avenida Insurgentes Centro, Tabacalera, Cuauhtémoc, Ciudad de México, 06030, México',
 'Metrobús Linea 1, Santa Isabel Tola, Gustavo A. Madero, Ciudad de México, 07010, México',
 'Metrobús Linea 1, Santa Isabel Tola, Gustavo A. Madero, Ciudad de México, 07010, México',
 'Metrobús Linea 2, San Miguel Chapultepec, Miguel Hidalgo, Ciudad de México, 11850, México',
 'Calzada San Juan de Aragón, Granjas Modernas, Gustavo A. Madero, Ciudad de México, 07460, México',
 'Calzada San Juan de Aragón, Granjas Modernas, Gustavo A. Madero, Ciudad de México, 07460, México',
 'Metrobús Linea 2, Escandón, Miguel Hidalgo, Ciudad de México, 11800, México',
 'Metrobús Linea 2, Hipódromo de la Condesa, Cuauhtémoc, Ciudad de México, 06170, México',
 'Metrobús Linea 2, Cuchillas del Moral II y III, Iztapalapa, Ciudad de México, 09319, México',
 'Avenida San Rafael Atlixco, Dr. Alfonso Ortiz Tirado, Iztapalapa, Ciudad de México, 09020, México',
 'Metrobús, Narvarte Poniente, Benito Juárez, Ciudad de México, 03020, México',
 'Metrobús Linea 2, INFONAVIT Sur 20, Iztacalco, Ciudad de México, 08580, México',
 'Andrés Molina, Metrobús, Nueva Santa Anita, Iztacalco, Ciudad de México, 08210, México',
 'Avenida Té, Ex Ejido Magdalena Mixhuca, Iztacalco, Ciudad de México, 08010, México',
 'Cafe Fuerte, Xola, Narvarte Oriente, Benito Juárez, Ciudad de México, 03023, México',
 'Metrobús Linea 1, Insurgentes Mixcoac, Benito Juárez, Ciudad de México, 03920, México',
 'mercado rastro, Avenida Ingeniero Eduardo Molina, 2o. tramo 20 de Noviembre, Venustiano Carranza, Ciudad de México, 15300, México',
 'Tepalcates, Metrobús Linea 2, Guelatao Benito Juárez, Iztapalapa, Ciudad de México, 09229, México',
 'Metrobús Linea 2, Iztapalapa, Ciudad de México, 09210, México',
 '76, Calle Gobernador Agustín Vicente Eguía, San Miguel Chapultepec, Miguel Hidalgo, Ciudad de México, 11850, México',
 'Serradell Primaria, Avenida Benjamín Franklin, Hipódromo de la Condesa, Cuauhtémoc, Ciudad de México, 06170, México',
 'Tacubaya, Avenida Parque Lira, Tacubaya, Miguel Hidalgo, Ciudad de México, 11870, México',
 'Xola, Metrobús, Unidad Habitacional IMSS Narvarte, Benito Juárez, Ciudad de México, 03023, México',
 'Metrobús Linea 2, Reforma Educativa, Iztapalapa, Ciudad de México, 09219, México',
 'Metrobús, Gabriel Ramos Millán Sección Tlacotal, Iztacalco, Ciudad de México, 08730, México',
 'Calzada Vallejo, Ampliación Progreso Nacional, Gustavo A. Madero, Ciudad de México, 07650, México',
 'Prolongación Guerrero, San Simón Tolnahuac, Cuauhtémoc, Ciudad de México, 06920, México',
 'Coltongo, Calzada Vallejo, El Porvenir, Azcapotzalco, Ciudad de México, 02940, México',
 'Etiopía / Plaza de la transparencia, Cuauhtémoc, Narvarte Poniente, Benito Juárez, Ciudad de México, 03020, México',
 'Calzada Vallejo, El Porvenir, Azcapotzalco, Ciudad de México, 02940, México',
 'Hotel Lepanto, Guerrero, Buenavista, Cuauhtémoc, Ciudad de México, 06350, México',
 'Calle Buenavista, Buenavista, Cuauhtémoc, Ciudad de México, 06350, México',
 'Cecilio Robelo, Avenida Congreso de la Unión, Morelos II, Venustiano Carranza, Ciudad de México, 15280, México',
 'Avenida Hidalgo, Tabacalera, Cuauhtémoc, Ciudad de México, 06030, México',
 'Cafe Villarias, 68, Calle Ayuntamiento, Centro Urbano, Cuauhtémoc, Ciudad de México, 06010, México',
 'San Lázaro, Avenida Ingeniero Eduardo Molina, 7 de Julio, Venustiano Carranza, Ciudad de México, 15390, México',
 'IEMS "José Revueltas Sánchez", Calle Sidar y Rovirosa, Morazán, Venustiano Carranza, Ciudad de México, 15100, México',
 'San Lázaro Buena Vista ruta Sur, Avenida Ingeniero Eduardo Molina, 10 de Mayo, Venustiano Carranza, Ciudad de México, 15290, México',
 'Nacional Monte de Piedad, Avenida Puente de Alvarado, Tabacalera, Cuauhtémoc, Ciudad de México, 06030, México',
 'Avenida San Pablo, Centro Urbano, Cuauhtémoc, Ciudad de México, 06010, México',
 'Avenida Congreso de la Unión, Morazán, Venustiano Carranza, Ciudad de México, 15100, México',
 'Templo de San Agustín, Calle República de El Salvador, Centro Urbano, Cuauhtémoc, Ciudad de México, 06010, México',
 '2, Avenida Ingeniero Eduardo Molina, Vasco de Quiroga, Gustavo A. Madero, Ciudad de México, 07440, México',
 'Avenida Ingeniero Eduardo Molina, Juan González Romero, Gustavo A. Madero, Ciudad de México, 07410, México',
 'Calle Oriente 95, Ampliación Mártires de Río Blanco, Gustavo A. Madero, Ciudad de México, 07859, México',
 'Avenida de las Culturas, Azcapotzalco, Tlalnepantla, Tlalnepantla de Baz, Estado de México, 02125, México',
 'Volcán de Fuego, Avenida Francisco Morazán, Ampliación Providencia, Gustavo A. Madero, Ciudad de México, 07560, México',
 'Poniente 140, Industrial Vallejo, Azcapotzalco, Ciudad de México, 02300, México',
 'San Bartolo, Avenida Montevideo, San Bartolo Atepehuacan, Gustavo A. Madero, Ciudad de México, 07730, México',
 'Triunfo de la República, Gustavo A. Madero, Ciudad de México, 07069, México',
 'Riobamba, Avenida Montevideo, Tepeyac Insurgentes, Gustavo A. Madero, Ciudad de México, 07020, México',
 'El Rosario, Calle Cultura Norte, El Rosario CROC VI Oyameles, Azcapotzalco, Ciudad de México, 02100, México',
 'Industronic, Poniente 140, San Andrés de Las Salinas, Gustavo A. Madero, Ciudad de México, 02320, México',
 '680, Avenida Francisco Morazán, Malvinas Mexicanas, Gustavo A. Madero, Ciudad de México, 07509, México',
 'N/A',
 'Calle Cultura Norte, El Rosario CROC VIII, Azcapotzalco, Ciudad de México, 02100, México',
 'Avenida Francisco Morazán, Malvinas Mexicanas, Gustavo A. Madero, Ciudad de México, 07509, México',
 'Metrobús Línea 7, 7 de Noviembre, Gustavo A. Madero, Ciudad de México, 07840, México',
 '43, Calle Hidalgo, Triunfo de la República, Gustavo A. Madero, Ciudad de México, 07069, México',
 'La Palma, Metrobús Línea 7, Tabacalera, Cuauhtémoc, Ciudad de México, 06030, México',
 'Chapultepec, Metrobús Línea 7, Tabacalera, Cuauhtémoc, Ciudad de México, 06030, México',
 'Avenida Paseo de la Reforma, Juárez, Cuauhtémoc, Ciudad de México, 06600, México',
 'Indios Verdes, Metrobús Línea 7, Rosas del Tepeyac, Gustavo A. Madero, Ciudad de México, 07010, México',
 'Avenida Paseo de la Reforma Norte, Tabacalera, Cuauhtémoc, Ciudad de México, 06030, México',
 'Campo Marte, Metrobús Línea 7, Polanco Chapultepec, Miguel Hidalgo, Ciudad de México, 11560, México',
 'Calzada de los Misterios, Industrial, Gustavo A. Madero, Ciudad de México, 07800, México',
 'Calzada Ticomán, Rosas del Tepeyac, Gustavo A. Madero, Ciudad de México, 07010, México',
 'N/A',
 'Indios Verdes, Metrobús Línea 7, Rosas del Tepeyac, Gustavo A. Madero, Ciudad de México, 07010, México',
 'Avenida Paseo de la Reforma, Polanco Chapultepec, Miguel Hidalgo, Ciudad de México, 11560, México',
 'Metrobús Linea 1, Noche Buena, Benito Juárez, Ciudad de México, 03720, México',
 'Avenida Sonora, Hipódromo, Cuauhtémoc, Ciudad de México, 06100, México',
 'Avenida Insurgentes Sur, Zona Arqueológica de Cuicuilco, Tlalpan, Ciudad de México, 14060, México',
 'Durango, Metrobús Línea 1, Roma Norte, Cuauhtémoc, Ciudad de México, 06700, México',
 'Metrobús Línea 1, Roma Norte, Cuauhtémoc, Ciudad de México, 06700, México',
 'Metrobús Linea 1, Tepeyac Insurgentes, Gustavo A. Madero, Ciudad de México, 07020, México',
 '1940, Avenida Insurgentes Sur, Guadalupe Inn, Álvaro Obregón, Ciudad de México, 01020, México',
 'Metrobús Linea 1, Unidad Habitacional Residencial Insurgentes Sur, Tlalpan, Ciudad de México, 14430, México',
 'Metrobús Linea 1, Santa Isabel Tola, Gustavo A. Madero, Ciudad de México, 07010, México',
 'SEDESOL - DICONSA, Avenida Insurgentes Sur, Peña Pobre, Tlalpan, Ciudad de México, 14060, México',
 'Transbordo Intermodal MB Álvaro Obregón, Roma Norte, Cuauhtémoc, Ciudad de México, 06700, México',
 'Carril Bus-Bici, Unidad Habitacional Nonoalco Tlatelolco, Cuauhtémoc, Ciudad de México, 06900, México',
 'Konditori, 1261, Avenida Insurgentes Sur, Tlacoquemecatl, Benito Juárez, Ciudad de México, 03200, México',
 'Avenida Constitución de Apatzingán, Reforma Educativa, Iztapalapa, Ciudad de México, 09219, México',
 'Xola, Unidad Habitacional IMSS Narvarte, Benito Juárez, Ciudad de México, 03023, México',
 'Metrobús Linea 2, Reforma Educativa, Iztapalapa, Ciudad de México, 09219, México',
 'Avenida Constitución de Apatzingán, Reforma Educativa, Iztapalapa, Ciudad de México, 09219, México',
 'Avenida San Rafael Atlixco, Dr. Alfonso Ortiz Tirado, Iztapalapa, Ciudad de México, 09020, México',
 'Metrobús Linea 2, Unidad Habitacional Ejército Constitucionalista, Iztapalapa, Ciudad de México, 09220, México',
 'Metrobús Linea 2, Reforma Educativa, Iztapalapa, Ciudad de México, 09219, México',
 'Metrobús Linea 2, INFONAVIT Sur 20, Iztacalco, Ciudad de México, 08580, México',
 'Villa de Aragón, Avenida Francisco Morazán, Villa de Aragón, Gustavo A. Madero, Ciudad de México, 07570, México',
 'Andrés Molina, Metrobús, Nueva Santa Anita, Iztacalco, Ciudad de México, 08210, México',
 'Metrobús Linea 2, Observatorio, Miguel Hidalgo, Ciudad de México, 11870, México',
 'Potzolcalli, Avenida Cuauhtémoc, Centro Urbano Benito Juárez, Cuauhtémoc, Ciudad de México, 06740, México',
 'Avenida Balderas, Tabacalera, Cuauhtémoc, Ciudad de México, 06030, México',
 'Avenida Cuauhtémoc, Doctores, Cuauhtémoc, Ciudad de México, 06720, México',
 'Pan el saso, Calzada Vallejo, Magdalena de Las Salinas, Gustavo A. Madero, Ciudad de México, 07760, México',
 'Montevideo, Calzada Vallejo, San Andrés de Las Salinas, Azcapotzalco, Ciudad de México, 02320, México',
 '1856, Calzada Vallejo, Gustavo A. Madero, Ciudad de México, 07640, México',
 'Guerrero, Buenavista, Cuauhtémoc, Ciudad de México, 06350, México',
 'Calzada Vallejo, Vallejo Poniente, Gustavo A. Madero, Ciudad de México, 07790, México',
 'Avenida Balderas, Tabacalera, Cuauhtémoc, Ciudad de México, 06030, México',
 'Mercado de Artesanías de La Ciudadela, Calle Ayuntamiento, Tabacalera, Cuauhtémoc, Ciudad de México, 06030, México',
 'Cafe Villarias, 68, Calle Ayuntamiento, Centro Urbano, Cuauhtémoc, Ciudad de México, 06010, México',
 'El Mesón de Belosario 38 Traditional comida Mexicana, 38, Calle Belisario Domínguez, Centro Urbano, Cuauhtémoc, Ciudad de México, 06010, México',
 'XEW-AM, Calle Ayuntamiento, Centro Urbano, Cuauhtémoc, Ciudad de México, 06010, México',
 'Mercado Sonora, Calle Juan Cuamatzín, Morazán, Venustiano Carranza, Ciudad de México, 15100, México',
 'Ecobici, Calle Carlos J. Meneses, Buenavista, Cuauhtémoc, Ciudad de México, 06350, México',
 'Teatro del Pueblo, Calle General Miguel Alemán, Cuauhtémoc, Ciudad de México, 15299, México',
 'Metrobús Linea 4, Avenida Jesús García, Buenavista, Cuauhtémoc, Ciudad de México, 06350, México',
 'Deportivo Eduardo Molina, Avenida Ingeniero Eduardo Molina, Ampliación 20 de Noviembre, Venustiano Carranza, Ciudad de México, 15260, México',
 'Avenida Ingeniero Eduardo Molina, DM Nacional, Gustavo A. Madero, Ciudad de México, 07450, México',
 'Avenida Río de los Remedios, Juan González Romero, Gustavo A. Madero, Ciudad de México, 07410, México',
 'Vasco de Quiroga, Metro Bus, Avenida Ingeniero Eduardo Molina, Vasco de Quiroga, Gustavo A. Madero, Ciudad de México, 07440, México',
 'Villa de Aragón, Avenida Francisco Morazán, Villa de Aragón, Gustavo A. Madero, Ciudad de México, 07570, México',
 'Casas Alemán, Transbordo intermodal MB Lucas Alemán - TB, FOVISSSTE Río de Guadalupe, Gustavo A. Madero, Ciudad de México, 07950, México',
 'Poniente 140, Industrial Vallejo, Azcapotzalco, Ciudad de México, 02300, México',
 'Tecnoparque, Deportivo Reynosa, Santa Bárbara, Azcapotzalco, Ciudad de México, 02230, México',
 'Calle Cultura Norte, El Rosario CROC VI Oyameles, Azcapotzalco, Ciudad de México, 02100, México',
 'Calzada San Juan de Aragón, San Juan de Aragón, Gustavo A. Madero, Ciudad de México, 07950, México',
 'Avenida de las Culturas, Hipódromo Textil, Azcapotzalco, Ciudad de México, 02100, México',
 'Total, Poniente 140, Industrial Vallejo, Azcapotzalco, Ciudad de México, 02300, México',
 'Calzada San Juan de Aragón, 15 de Agosto, Gustavo A. Madero, Ciudad de México, 07058, México',
 'Loreto Fabela, Avenida Río Guadalupe, San Juan de Aragón, Gustavo A. Madero, Ciudad de México, 07950, México',
 'Excélsior, Calzada de los Misterios (Metrobús Línea 7), Industrial, Gustavo A. Madero, Ciudad de México, 07800, México',
 'Avenida Cantera, Triunfo de la República, Gustavo A. Madero, Ciudad de México, 07069, México',
 'Clave, Calzada de los Misterios, 7 de Noviembre, Gustavo A. Madero, Ciudad de México, 07840, México',
 'Avenida Paseo de la Reforma, Tabacalera, Cuauhtémoc, Ciudad de México, 06030, México',
 'Avenida Paseo de la Reforma, Cuauhtémoc, Ciudad de México, 06500, México',
 'Calzada de los Misterios, Tepeyac Insurgentes, Gustavo A. Madero, Ciudad de México, 07020, México',
 'Avenida Paseo de la Reforma, Nueva Anzures, Miguel Hidalgo, Ciudad de México, 11590, México',
 'Hospital Infantil La Villa, Metrobús Línea 7, Triunfo de la República, Gustavo A. Madero, Ciudad de México, 07069, México',
 'Indios Verdes, Metrobús Línea 7, Rosas del Tepeyac, Gustavo A. Madero, Ciudad de México, 07010, México',
 'Avenida Paseo de la Reforma, Polanco Chapultepec, Miguel Hidalgo, Ciudad de México, 11560, México',
 'Metrobús Linea 1, Tepeyac Insurgentes, Gustavo A. Madero, Ciudad de México, 07020, México',
 'Avenida Insurgentes Centro, Juárez, Cuauhtémoc, Ciudad de México, 06600, México',
 'Inbursa, Avenida Insurgentes Sur, Peña Pobre, Tlalpan, Ciudad de México, 14060, México',
 'El Caminero, Metrobús Linea 1, Barrio El Truenito, Tlalpan, Ciudad de México, 14430, México',
 'Metrobús Linea 1, Santa Isabel Tola, Gustavo A. Madero, Ciudad de México, 07010, México',
 'Hotel City Express, Avenida Insurgentes Sur, Crédito constructor, Benito Juárez, Ciudad de México, 03940, México',
 'Buenavista, Metrobús Línea 1, Buenavista, Cuauhtémoc, Ciudad de México, 06350, México',
 'Oxxo, Avenida Insurgentes Centro, Tabacalera, Cuauhtémoc, Ciudad de México, 06030, México',
 'Metrobús Linea 1, Santa Isabel Tola, Gustavo A. Madero, Ciudad de México, 07010, México',
 'Metrobús Linea 2, Reforma Educativa, Iztapalapa, Ciudad de México, 09219, México',
 'Metrobús, Nueva Santa Anita, Iztacalco, Ciudad de México, 08210, México',
 'Avenida Presidente Plutarco Elías Calles, Tlazintla, Iztacalco, Ciudad de México, 08710, México',
 'Avenida Constitución de Apatzingán, Reforma Educativa, Iztapalapa, Ciudad de México, 09219, México',
 'Metrobús, Ex Ejido Magdalena Mixhuca, Iztacalco, Ciudad de México, 08010, México',
 'Metrobús Linea 2, Hipódromo, Cuauhtémoc, Ciudad de México, 06100, México',
 'Tepalcates, Metrobús Linea 2, Guelatao Benito Juárez, Iztapalapa, Ciudad de México, 09229, México',

In [29]:
#other = []
#count = 0
#for i in list_aux:
#    print(count)
#    alcaldia = geolocaliza(i)
#    other.append(alcaldia)
#    count+=1

In [54]:
data['alcaldia'] = alcaldia
data['ubicacion'] = ubicacion

In [55]:
ubicacion[0]

'Universidad Nacional Autónoma de México, Circuito Exterior, Ciudad Universitaria, Coyoacán, Ciudad de México, 04360, México'

In [56]:
data

,id,date_updated,vehicle_id,vehicle_label,vehicle_current_status,position_latitude,position_longitude,geographic_point,position_speed,position_odometer,trip_schedule_relationship,trip_id,trip_start_date,trip_route_id,alcaldia,ubicacion
0,0,2021-01-27 18:00:02,170,112,2,19.317499,-99.187798,"19.3174991608,-99.1877975464",16,231,2,NaN,NaN,367.0,Coyoacán,"Universidad Nacional Autónoma de México, Circu..."
1,1,2021-01-27 18:00:02,177,119,1,19.292601,-99.177498,"19.2926006317,-99.1774978638",13,0,0,9732304.0,20200428.0,367.0,Tlalpan,"Ayuntamiento, Avenida Insurgentes Sur, Tlalpan..."
2,2,2021-01-27 18:00:02,1286,219,2,19.450100,-99.110100,"19.4500999451,-99.1100997925",5,0,0,9678929.0,20200428.0,161.0,Venustiano Carranza,"Avenida Ingeniero Eduardo Molina, 2o. tramo 20..."
3,3,2021-01-27 18:00:02,1302,235,1,19.389200,-99.059799,"19.3892002106,-99.0597991943",4,0,0,9738091.0,20200428.0,301.0,Iztapalapa,"Metrobús Linea 2, Unidad Habitacional Ejército..."
4,4,2021-01-27 18:00:02,361,303,2,19.382601,-99.061302,"19.3826007843,-99.0613021851",0,454,0,9738145.0,20200428.0,301.0,Iztapalapa,"Avenida Canal de Tezontle, Leyes de Reforma 3a..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
202,202,2021-01-27 18:00:02,1238,2347,2,19.403500,-99.169899,"19.4034996033,-99.1698989868",7,0,0,9736129.0,20200428.0,301.0,Cuauhtémoc,"Metrobús Linea 2, Hipódromo, Cuauhtémoc, Ciuda..."
203,203,2021-01-27 18:00:02,1024,2351,2,19.390900,-99.047302,"19.3908996582,-99.0473022461",0,0,0,9737808.0,20200428.0,301.0,Iztapalapa,"Tepalcates, Metrobús Linea 2, Guelatao Benito ..."
204,204,2021-01-27 18:00:02,10002,2358,2,19.397301,-99.104599,"19.3973007202,-99.104598999",7,0,0,9737246.0,20200428.0,301.0,Iztacalco,"Metrobús, Gabriel Ramos Millán Sección Tlacota..."
205,205,2021-01-27 18:00:02,1232,2363,2,19.393900,-99.137497,"19.3938999176,-99.1374969482",14,0,0,9735896.0,20200428.0,301.0,Benito Juárez,"Metrobús, Moderna, Benito Juárez, Ciudad de Mé..."
206,206,2021-01-27 18:00:02,1235,2366,2,19.395100,-99.145798,"19.3950996399,-99.1457977295",0,276,0,9736965.0,20200428.0,301.0,Benito Juárez,"Xola, Unidad Habitacional IMSS Narvarte, Benit..."

In [1]:
import sqlite3

In [59]:
conn = sqlite3.connect('TestDB1_1_1.db')
c = conn.cursor()

c.execute('CREATE TABLE MBUS (id number, date_updated timestamp, vehicle_id number, vehicle_label number, vehicle_current_status number, position_latitude number, position_longitude number, geographic_point number, position_speed number, position_odometer number, trip_schedule_relationship number, trip_id number, trip_start_date number, trip_route_id number, alcaldia text, ubicacion text)')
conn.commit()

In [60]:
data.to_sql('MBUS', conn, if_exists='replace', index = False)

In [61]:
st = 'MBUS'
c.execute("SELECT * FROM "+st)

In [62]:
c.execute("SELECT DISTINCT vehicle_id FROM "+st)

In [63]:
list_2 = c.fetchall()

In [64]:
unidades = [i[0] for i in list_2]

In [65]:
unidades

[170,
 177,
 1286,
 1302,
 361,
 370,
 371,
 409,
 449,
 1,
 33,
 38,
 39,
 40,
 53,
 1148,
 1149,
 981,
 982,
 984,
 985,
 467,
 483,
 486,
 490,
 491,
 492,
 496,
 512,
 557,
 562,
 10000,
 1085,
 1115,
 1120,
 1132,
 702,
 705,
 713,
 716,
 753,
 757,
 760,
 766,
 787,
 789,
 1253,
 531,
 1174,
 1160,
 1165,
 988,
 990,
 1220,
 1067,
 1069,
 1188,
 1190,
 1191,
 1236,
 1214,
 1217,
 10007,
 1237,
 1025,
 1230,
 1233,
 1241,
 178,
 1287,
 1288,
 366,
 416,
 422,
 432,
 450,
 452,
 1021,
 24,
 26,
 35,
 51,
 56,
 986,
 472,
 474,
 476,
 482,
 499,
 500,
 501,
 502,
 505,
 508,
 511,
 558,
 561,
 1179,
 1075,
 1079,
 1089,
 1091,
 1180,
 1181,
 1185,
 1117,
 1122,
 1135,
 1141,
 1144,
 1146,
 711,
 714,
 719,
 730,
 745,
 749,
 770,
 771,
 774,
 781,
 788,
 790,
 992,
 997,
 10016,
 10019,
 10023,
 1159,
 1255,
 1257,
 1259,
 1177,
 1164,
 1167,
 1070,
 1062,
 10015,
 1186,
 1192,
 930,
 1234,
 1289,
 367,
 375,
 1018,
 398,
 3,
 20,
 22,
 23,
 28,
 37,
 1147,
 1151,
 1152,
 473,
 475,
 484,
 494,
 497,
 504,
 506,
 509,
 544,
 545,
 559,
 560,
 1074,
 1078,
 1084,
 1100,
 1101,
 1184,
 1110,
 1112,
 1126,
 1130,
 701,
 717,
 720,
 721,
 728,
 737,
 746,
 754,
 758,
 764,
 777,
 523,
 533,
 1254,
 1256,
 1044,
 1248,
 1284,
 1072,
 1216,
 1218,
 1225,
 1226,
 1227,
 1238,
 1024,
 10002,
 1232,
 1235]

In [66]:
c.execute("SELECT DISTINCT alcaldia FROM "+st)

In [67]:
list_2aux = c.fetchall()

In [68]:
alcaldia_ = [i[0] for i in list_2aux]

In [69]:
alcaldia_

[' Coyoacán',
 ' Tlalpan',
 ' Venustiano Carranza',
 ' Iztapalapa',
 ' Nezahualcóyotl',
 ' Miguel Hidalgo',
 ' Cuauhtémoc',
 ' Gustavo A. Madero',
 ' Benito Juárez',
 ' Tlalnepantla de Baz',
 ' Azcapotzalco',
 ' Iztacalco',
 'N/A',
 ' Álvaro Obregón']

In [70]:
alc = "tlalpan"

In [71]:
c.execute("SELECT vehicle_id FROM "+st+" WHERE alcaldia LIKE '%"+alc+"%'")#"+alc)

In [72]:
u_id = c.fetchall()

In [73]:
unidades_alc = [i[0] for i in u_id]

In [74]:
unidades_alc

[177, 531, 990, 10016, 1257, 1177, 533, 1254]

In [48]:
from pandas import DataFrame
#columns.append('alcaldia')
df = DataFrame(c.fetchall(), columns=columns)

In [49]:
df

,id,date_updated,vehicle_id,vehicle_label,vehicle_current_status,position_latitude,position_longitude,geographic_point,position_speed,position_odometer,trip_schedule_relationship,trip_id,trip_start_date,trip_route_id,alcaldia
0,0,2021-01-27 18:00:02,170,112,2,19.317499,-99.187798,"19.3174991608,-99.1877975464",16,231,2,NaN,NaN,367.0,coyoacán
1,1,2021-01-27 18:00:02,177,119,1,19.292601,-99.177498,"19.2926006317,-99.1774978638",13,0,0,9732304.0,20200428.0,367.0,tlalpan
2,2,2021-01-27 18:00:02,1286,219,2,19.450100,-99.110100,"19.4500999451,-99.1100997925",5,0,0,9678929.0,20200428.0,161.0,venustiano carranza
3,3,2021-01-27 18:00:02,1302,235,1,19.389200,-99.059799,"19.3892002106,-99.0597991943",4,0,0,9738091.0,20200428.0,301.0,iztapalapa
4,4,2021-01-27 18:00:02,361,303,2,19.382601,-99.061302,"19.3826007843,-99.0613021851",0,454,0,9738145.0,20200428.0,301.0,iztapalapa
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
202,202,2021-01-27 18:00:02,1238,2347,2,19.403500,-99.169899,"19.4034996033,-99.1698989868",7,0,0,9736129.0,20200428.0,301.0,cuauhtémoc
203,203,2021-01-27 18:00:02,1024,2351,2,19.390900,-99.047302,"19.3908996582,-99.0473022461",0,0,0,9737808.0,20200428.0,301.0,iztapalapa
204,204,2021-01-27 18:00:02,10002,2358,2,19.397301,-99.104599,"19.3973007202,-99.104598999",7,0,0,9737246.0,20200428.0,301.0,iztacalco
205,205,2021-01-27 18:00:02,1232,2363,2,19.393900,-99.137497,"19.3938999176,-99.1374969482",14,0,0,9735896.0,20200428.0,301.0,benito juárez
206,206,2021-01-27 18:00:02,1235,2366,2,19.395100,-99.145798,"19.3950996399,-99.1457977295",0,276,0,9736965.0,20200428.0,301.0,benito juárez

In [2]:
import sqlite3

In [3]:
conn = sqlite3.connect('TestDB1_1.db')
c = conn.cursor()

In [4]:
ids = "20"

In [7]:
c.execute("SELECT date_updated, ubicacion FROM MBUS WHERE vehicle_id LIKE '%"+ids+"%'")#"+applc)

In [8]:
l_a = c.fetchall()

In [14]:
l_a[1][1]

'Oxxo, Avenida Insurgentes Centro, Tabacalera, Cuauhtémoc, Ciudad de México, 06030, México'

In [22]:
historial = [i[1] for i in l_a]

In [23]:
historial

['Instituto Politécnico Nacional, Avenida Montevideo, Lindavista, Gustavo A. Madero, Ciudad de México, 07300, México',
 'Oxxo, Avenida Insurgentes Centro, Tabacalera, Cuauhtémoc, Ciudad de México, 06030, México',
 'Avenida Balderas, Tabacalera, Cuauhtémoc, Ciudad de México, 06030, México',
 'Clave, Calzada de los Misterios, 7 de Noviembre, Gustavo A. Madero, Ciudad de México, 07840, México']